blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://discord.com/channels/1517052341700788254/1517052341700788260
    about: Please use Discussions for general questions.
